model_params:
  name: 'AggMM'
  embed_size: 128
  max_codes: 300
  embed_weights: "icd10_embeddings_128.csv"
  static_hidden: 64
  use_pretrain: True
  freeze_embed: False
  num_layers: 4
  num_heads: 8
  dropout: 0.1
  multiclass: True

data_params:
  max_codes: 300
  batch_size: 128
  num_workers: 4
  task: "AMR"

exp_params:
  LR: 0.0001
  weight_decay: 0.0
  scheduler_gamma: 0.95
  manual_seed: 4

trainer_params:
  max_epochs: 100
  accelerator: "auto"

logging_params:
  save_dir: "logs/"
  name: 'AggMM'